---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sms-sender
  name: sms-sender
spec:
  selector:
    matchLabels:
      app: sms-sender
  replicas: 1
  template:
    metadata:
      labels:
        app: sms-sender
    spec:
      serviceAccountName: bigdata
      containers:
        - name: sms-sender
          image: docker.io/kapkiai/sms-sender:0.0.3
          ports:
            - containerPort: 8085
          imagePullPolicy: Always
          env:
            - name: smppHost
              value: "10.33.14.33"
            - name: smppPort
              value: "5016"
            - name: smppSystemId
              value: "nifi"
            - name: smppPassword
              value: "N1F1"
---
apiVersion: v1
kind: Service
metadata:
  name: sms-sender
spec:
  type: LoadBalancer
  ports:
    - name: send-port
      port: 8085
      targetPort: 8085
      protocol: TCP
  selector:
    app: sms-sender


